name: macOS Web GUI
on: workflow_dispatch

jobs:
  gui:
    runs-on: macos-latest
    steps:
      - name: Set macOS Password
        run: |
          sudo sysadminctl -adminPassword "" -resetPasswordFor runneradmin -newPassword password123

      - name: Enable Screen Sharing
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on \
          -allowAccessFor -allUsers -privs -all

      - name: Install noVNC Gateway
        run: |
          pip3 install websockify
          git clone https://github.com

      - name: Start Tunnel and Web Proxy
        run: |
          # Start the bridge between VNC and Web
          ./noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 8080 &
          
          # Install and start Cloudflare
          brew install cloudflared
          cloudflared tunnel --url http://localhost:8080
