name: macOS Remote Access
on: workflow_dispatch

jobs:
  remote-access:
    runs-on: macos-latest
    steps:
      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Start SSH Server
        run: |
          sudo systemsetup -setremotelogin on

      - name: Establish Tunnel
        run: |
          echo "Starting tunnel..."
          echo "Run this on your PC: ssh -i \"C:\Users\Murat Saglam\.ssh\id_github_actions\" -J serveo.net runneradmin@macos_dogday17"
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R macos_dogday17:22:localhost:22 serveo.net sleep 3600
